name: Push_Container

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      aws_region:
        required: true
        type: string
      ecr_base_uri:
        required: true
        type: string
    secrets:
      aws_role:
        required: true

jobs:
  push_to_ecr:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Install AWS CLI
        id: install-aws-cli
        uses: unfor19/install-aws-cli-action@v1
      - name: Assume AWS Role
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.aws_role }}
          aws-region: ${{ inputs.aws-region }}
      - name: Docker Login
        run: aws ecr get-login-password --region "${{ inputs.aws_region }}" | docker login --username AWS --password-stdin "${{ inputs.ecr_base_uri }}"
      - run: |
          docker tag "{{ inputs.ecr_base_uri }}/${{ inputs.image_name }}"
          docker push

