name: Version

on:
  workflow_call:
    inputs:
      part:
        required: true
        type: string
      branch_name:
        required: true
        type: string
      token:
        required: true
        type: string

permissions:
  contents: write
  pull-requests: write

jobs:
  bump_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch_name }}
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'
          architecture: 'x64'
          cache: 'pip'
      - run: pip install bump2version
      - run: bump2version --list ${{ inputs.part }}
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ inputs.token }}
          branch-suffix: short-commit-hash
          title: Bump ${{ inputs.part }} version
      - name: Approve Pull Request
        uses: juliangruber/approve-pull-request-action@v1.1.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ steps.cpr.outputs.pull-request-number }}
      - name: Merge Pull Request
        uses: juliangruber/merge-pull-request-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ steps.cpr.outputs.pull-request-number }}
