name: Version

on:
  workflow_call:
    inputs:
      part:
        required: true
        type: string
      branch_name:
        required: true
        type: string
    secrets:
      actions-token:
        required: true

permissions:
  contents: write
  pull-requests: write

jobs:
  bump_version:
    runs-on: ubuntu-latest
    steps:
      - run: |
          if [[ "${{secrets.actions-token}}" == "" ]]; then
            echo The secret does not exist
          else
            echo The secret exists
          fi
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch_name }}
          token: ${{ secrets.actions-token }}
      - name: Setup git user
        run: |
          git config --global user.name "prophia-bot"
          git config --global user.email "prophia-bot@users.noreply.github.com"
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'
          architecture: 'x64'
          cache: 'pip'
      - run: pip install bump2version
      - run: bump2version --verbose --commit --tag --list ${{ inputs.part }}
      - run: |
          git push origin
          git push origin --tags

