name: Yarn Version

on:
  workflow_call:
    inputs:
      part:
        required: true
        type: string
    secrets:
      actions-token:
        required: true

permissions:
  contents: write
  pull-requests: write

jobs:
  yarn_version:
    runs-on: ubuntu-latest
    steps:
      - run: |
          if [[ "${{secrets.actions-token}}" == "" ]]; then
            echo The secret does not exist
          else
            echo The secret exists
          fi
      - uses: actions/checkout@v3
        with:
          ref: develop
          token: ${{ secrets.actions-token }}
      - name: Setup git user
        run: |
          git config --global user.name "prophia-bot"
          git config --global user.email "prophia-bot@users.noreply.github.com"
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 12
          cache: 'npm'
      - run: npm install yarn -g
      - run: yarn install
      - name: Save previous version to env
        run: yarn save-previous-version
      - name: Update package.json
        run: yarn version --${{ inputs.part }} --no-git-tag-version
      - name: Save updated version to env
        run: yarn save-updated-version
      - name: Update .version file
        run: sed -i "s/$(cat .version)/${updated_version}/g" ./.version
      - name: Git commit and tag
        run: |
          git commit -am"Bump version $previous_version -> $updated_version"
          git tag -a v${updated_version} -m"Bump version $previous_version -> $updated_version"
      - name: Push branch and tag
        run: |
          git show --summary
          git push origin
          git push origin --tags
